# Generated by Django 5.1.7 on 2025-03-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combomeal',
            name='price',
        ),
    ]
