# Generated by Django 5.1.7 on 2025-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_remove_combomeal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combomeal',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='combomeal',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
