# Generated by Django 5.1.7 on 2025-03-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_remove_combomeal_is_available_alter_combomeal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='combomeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.combomeal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.product'),
        ),
    ]
